"""add followup assignment and priority

Revision ID: 00262bd3365e
Revises: 2a801ba2f327
Create Date: 2026-09-20 17:20:22.257656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00262bd3365e'
down_revision: Union[str, Sequence[str], None] = '2a801ba2f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followups', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.add_column('followups', sa.Column('priority', sa.String(length=20), nullable=False))
    op.alter_column('followups', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_followups_assigned_to_user_id'), 'followups', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_followups_created_at'), 'followups', ['created_at'], unique=False)
    op.create_index(op.f('ix_followups_priority'), 'followups', ['priority'], unique=False)
    op.create_index(op.f('ix_followups_scheduled_date'), 'followups', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_followups_status'), 'followups', ['status'], unique=False)
    op.create_foreign_key(None, 'followups', 'users', ['assigned_to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.drop_index(op.f('ix_followups_status'), table_name='followups')
    op.drop_index(op.f('ix_followups_scheduled_date'), table_name='followups')
    op.drop_index(op.f('ix_followups_priority'), table_name='followups')
    op.drop_index(op.f('ix_followups_created_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_assigned_to_user_id'), table_name='followups')
    op.alter_column('followups', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('followups', 'priority')
    op.drop_column('followups', 'assigned_to_user_id')
    # ### end Alembic commands ###
