"""create audit logs table

Revision ID: 2a801ba2f327
Revises: d1465e186ff8
Create Date: 2026-09-20 16:41:04.052338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a801ba2f327'
down_revision: Union[str, Sequence[str], None] = 'd1465e186ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###
