"""add screening image fields

Revision ID: 48717e1b27c8
Revises: 7f93ab179eed
Create Date: 2026-09-11 16:03:51.246096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48717e1b27c8'
down_revision: Union[str, Sequence[str], None] = '7f93ab179eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_cards_qr_code_value'), table_name='health_cards')
    op.drop_table('health_cards')
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'entity_id')
    op.add_column('followups', sa.Column('screening_id', sa.Integer(), nullable=True))
    op.add_column('followups', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('followups', sa.Column('completed_date', sa.DateTime(), nullable=True))
    op.alter_column('followups', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_index(op.f('ix_followups_patient_id'), 'followups', ['patient_id'], unique=False)
    op.create_index(op.f('ix_followups_screening_id'), 'followups', ['screening_id'], unique=False)
    op.drop_constraint(op.f('followups_assigned_to_fkey'), 'followups', type_='foreignkey')
    op.create_foreign_key(None, 'followups', 'screenings', ['screening_id'], ['id'])
    op.drop_column('followups', 'notification_status')
    op.drop_column('followups', 'completed_at')
    op.drop_column('followups', 'assigned_to')
    op.drop_column('followups', 'next_screening_date')
    op.add_column('model_versions', sa.Column('screening_type', sa.String(length=50), nullable=False))
    op.add_column('model_versions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('model_versions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('model_versions', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('model_versions', 'artifact_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_versions_screening_type'), 'model_versions', ['screening_type'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.drop_column('model_versions', 'metrics_json')
    op.alter_column('patients', 'symptoms',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'medical_history',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.add_column('screening_results', sa.Column('gradcam_path', sa.String(length=500), nullable=True))
    op.add_column('screening_results', sa.Column('explanation', sa.Text(), nullable=True))
    op.alter_column('screening_results', 'prediction',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('screening_results', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('screening_results', 'model_version',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_constraint(op.f('screening_results_screening_id_key'), 'screening_results', type_='unique')
    op.create_index(op.f('ix_screening_results_id'), 'screening_results', ['id'], unique=False)
    op.create_index(op.f('ix_screening_results_screening_id'), 'screening_results', ['screening_id'], unique=True)
    op.drop_constraint(op.f('screening_results_patient_id_fkey'), 'screening_results', type_='foreignkey')
    op.drop_column('screening_results', 'gradcam_reference')
    op.drop_column('screening_results', 'review_status')
    op.drop_column('screening_results', 'screening_type')
    op.drop_column('screening_results', 'recommendation')
    op.drop_column('screening_results', 'patient_id')
    op.drop_column('screening_results', 'image_reference')
    op.drop_column('screening_results', 'emergency_priority')
    op.add_column('screenings', sa.Column('image_reference', sa.String(length=500), nullable=True))
    op.add_column('screenings', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.add_column('screenings', sa.Column('image_size', sa.Integer(), nullable=True))
    op.add_column('screenings', sa.Column('image_width', sa.Integer(), nullable=True))
    op.add_column('screenings', sa.Column('image_height', sa.Integer(), nullable=True))
    op.alter_column('screenings', 'screening_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_screenings_id'), 'screenings', ['id'], unique=False)
    op.create_index(op.f('ix_screenings_patient_id'), 'screenings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_screenings_screening_type'), 'screenings', ['screening_type'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ASHA', 'ANM', 'ADMIN', name='role'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('users', 'village',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('users', 'village',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('ASHA', 'ANM', 'ADMIN', name='role'),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_screening_type'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_patient_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_id'), table_name='screenings')
    op.alter_column('screenings', 'screening_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('screenings', 'image_height')
    op.drop_column('screenings', 'image_width')
    op.drop_column('screenings', 'image_size')
    op.drop_column('screenings', 'image_filename')
    op.drop_column('screenings', 'image_reference')
    op.add_column('screening_results', sa.Column('emergency_priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('screening_results', sa.Column('image_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('screening_results', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('screening_results', sa.Column('screening_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('screening_results', sa.Column('review_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('screening_results', sa.Column('gradcam_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('screening_results_patient_id_fkey'), 'screening_results', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_screening_results_screening_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_id'), table_name='screening_results')
    op.create_unique_constraint(op.f('screening_results_screening_id_key'), 'screening_results', ['screening_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('screening_results', 'model_version',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('screening_results', 'risk_level',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('screening_results', 'prediction',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('screening_results', 'explanation')
    op.drop_column('screening_results', 'gradcam_path')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.alter_column('patients', 'medical_history',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'symptoms',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('model_versions', sa.Column('metrics_json', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_screening_type'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.alter_column('model_versions', 'artifact_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('model_versions', 'model_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('model_versions', 'is_active')
    op.drop_column('model_versions', 'description')
    op.drop_column('model_versions', 'screening_type')
    op.add_column('followups', sa.Column('next_screening_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('followups', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('followups', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('followups', sa.Column('notification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.create_foreign_key(op.f('followups_assigned_to_fkey'), 'followups', 'users', ['assigned_to'], ['id'])
    op.drop_index(op.f('ix_followups_screening_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_patient_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.alter_column('followups', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('followups', 'completed_date')
    op.drop_column('followups', 'scheduled_date')
    op.drop_column('followups', 'screening_id')
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('entity', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.create_table('health_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qr_code_value', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('health_cards_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('health_cards_pkey')),
    sa.UniqueConstraint('patient_id', name=op.f('health_cards_patient_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_health_cards_qr_code_value'), 'health_cards', ['qr_code_value'], unique=True)
    # ### end Alembic commands ###
